lib/mqtt.js, lib/server.js, test/mqtt.js
Solution to #137
* Remove support for `MqttSecureServer(path, path, callback)`, requires an options object
* Backwards compatibility added at the `mqtt.createSecureServer` level.
* Options object accepts the same keys as those passed into `tls.Server`, therefore the `fs.readFileSync`s to fetch the keys and certs are now pushed out to the user level
Stuff not done:
* Deprecation warning (if necessary?)
* Update docs
=> Accept an options object in `mqtt.createSecureServer`

lib/client.js
This is fine in node, but in the browser it loads the enormous crypto dependency when all that is needed is a random ID.  The `crypto.randomBytes` function is also not supported on older browsers, so it would seem more sensible to use the simpler `Math.random()` unless true cryptographic security is required for this ID.
=> Don't load "crypto" just for "randomBytes"

lib/connect/index.js, test/mqtt.js
- Nodes `url.parse` return `mqtts:` instead of the expected `mqtts`.
- The `wss` protocol configuration was missing.
- Added tests.
=> Fixed bugs caused by parsing the protocol from the URL

lib/connect/tls.js
@mcollina Found another one.
Maybe it would be better to have real servers to test against, kinda like an acceptance test?
I'm working on a `mqtt-server` module that builds upon the new mqtt-connection. Wanna release that one under the mqttjs organization, and use it for tests?
=> `tls.connect` first expects the host property

lib/connect/ws.js
This became an issue with for example `fubar` which does not allow WebSocket connections on any path but `/mqtt`. :stuck_out_tongue_winking_eye:
=> Handle paths properly

lib/client.js, test/abstract_client.js
2nd try first request build failed... added one last change . Test seems to be effective at catching problem without fix, but did not see offline event as expected to fail the test. Instead when it fails the test just times out.
=> fix and test for issue 252 (retry)

README.md
Updated API description according to current rev of https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js
NOTE: API description on npm package page is also outdated.
=> Updated Client.publish API description

lib/connect/ws.js
Checks for presence of browser environment before attempting document.URL
=> Web Worker support.

README.md, package.json
- Update README.md
- Fix package.json
If we don't set `browser.fs`, `browser.net`, `browser.tls` in package.json, it will complain about module not found at bundling time.
```
ERROR in ./lib/connect/tls.js
Module not found: Error: Cannot resolve module 'tls' in /tmp/MQTT.js/lib/connect
@ ./lib/connect/tls.js 2:10-24
ERROR in ./lib/connect/tcp.js
Module not found: Error: Cannot resolve module 'net' in /tmp/MQTT.js/lib/connect
@ ./lib/connect/tcp.js 2:10-24
```
ref: webpack/webpack#744
=> Add Webpack support without errors.

README.md
Hey thanks for making this available.
Just noticed you are using the png version of the build status badge, while travis actually offers a svg version. On retina-style screens this looks a lot better with svg :)
So here is a very minor PR changing the badge to the svg version. If you think it is a good idea, feel free. If not, no biggie.
Thanks again, have a nice day!
=> Use svg version of travis badge

lib/client.js
Moving the default of the publish callback to nop. The defaulting is still done for the qos 1/2 callbacks, but under qos 0, the callback is left undefined so as to not add nop event handlers to the 'drain' event on the stream when the stream is buffering.
I don't believe this effects any situation except for when:
- publishing with no callback in qos 0
- when the stream is not ready to write to
in this situation it doesn't add a 'drain' listener to the write stream
=> Prevent unecessary 'drain' listeners on the write stream when buffering publishes in qos 0 with no callback

lib/client.js
10 listeners is quite easily not enough on an intermittent connection when each publish callback requires a drain listener.
=> Increase max listeners on stream to 1000

README.md, lib/client.js, test/abstract_client.js
After making connection client needs to know if there exists its stored session in server side. Flag is avaliable in packet, however it should be passed to event as argument. For future needs argument type is object.
=> Session Present flag is needed while handling connect event

lib/connect/tls.js
I believe this is much easier to read and it complies with the check-style rules. It's important that a reader can understand this line and that the default setting is true.
=> Simplify rejectUnauthorized defaulting by using `!== false`

lib/client.js, package.json, test/abstract_client.js
Fixes #353 
Let's say that the client has a keepalive of 10 seconds,
Until now, it would send ping every 10 seconds.
Now, if it has received a control packet at 3 seconds, it'll send the next ping at 13s, so it results in a reduced data consumption.
Fixes #354 
Fixes #346
=> Change keep alive, deleted jshint errors, fixed reconnectPeriod >= connectTimeout bug

lib/client.js, test/abstract_client.js
Fixes #357
Fixes #359 
As said in the documentation, the ping should be rescheduled when sending packets, not on packet receive.
> It is the responsibility of the Client to ensure that the interval between Control Packets being sent does not exceed the Keep Alive value. In the absence of sending any other Control Packets, the Client MUST send a PINGREQ Packet [MQTT-3.1.2-23]
Here is an emitter client. It sends packet every seconds. There wasn't any problem with this one.
```js
var mqtt    = require('./');
var client  = mqtt.connect('mqtt://test.mosquitto.org', {keepalive: 1});
client.on('message', function (topic, message) {
console.log(message.toString());
});
client.on('disconnect', function () {
console.log('DISCONNECTION');
});
var i = 0;
setInterval(function () { …
```
=> Fixed the ping rescheduling

lib/client.js, test/abstract_client.js
If `MqttClient.subscribe` is called with a topic and options object, but no callback function, then the options object is being passed to `_checkDisconnect` as the callback. If the client is currently disconnecting then this results in `TypeError: object is not a function` as it tries to invoke the callback which is actually the options object.
The `subscribe` function already does the necessary work to properly set `opts` and `callback` depending on what was passed into the function, but the call to `_checkDisconnect` happens before that is done.
This fix moves the call to `_checkDisconnect` to below the point where callback will be guaranteed to be a function.
=> Ensure subscribe callback is set before checkDisconnect

lib/client.js
Shouldn't the connack timeout be cleared if a close event is received?  If it isn't cleared, it can interrupt a reconnect attempt in progress.
=> Clear the connack timeout on close event

README.md
I created a TypeScript type definition of the MQTT.js a while ago. It can be found in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository. This instance provides a badge for a project, which has a type definition.
Instead of the experimental badge, one could just mention about the type definitions somewhere in the text or just leave the README as it is.
=> Added DefinitelyTyped badge to README.md

lib/connect/ws.js
Added options to pass ca, cert, and key options to the underlying websocket-stream instance. This allows use with self-signed CAs and certificate based client authentication.
Tested against a mosquitto install, but not sure how to test as part of this project as the server does not appear to (currently) support wss.
=> Fix to support TLS server and client auth for wss://

README.md, lib/client.js, test/abstract_client.js
If the client publishes faster than the keepalive interval, PINGREQ messages keep getting rescheduled and will not be sent.  If connectivity is lost between the client and the broker during such a period, the client may not be able to detect that its published messages aren't reaching the broker.  This change introduces a new option ('fastClientDisconnectDetect') to **not** reschedule PINGREQ messages when sending packets.
This is in accordance with the MQTT spec v3.1.1, paragraph 3.1.2.10 (Keep Alive), which states that clients may send PINGREQ at any time:
```
The Client can send PINGREQ at any time, irrespective of the Keep Alive value, and use the PINGRESP to determine that the network and the Server are working.
```
=> Introduce 'fastClientDisconnectDetect' option

README.md, lib/client.js, test/abstract_client.js
My proposal for #397
The default behavior remains identical to existing behavior. If a client's .qosZeroNotQueued option is set to true, then it will stop queuing QoS zero messages, but will still queue QoS 1 and 2 messages if disconnected.
I wasn't sure what branch to put this in, and it isn't a breaking change, so I put it in master. Let me know if it should go somewhere else.
=> Add .qosZeroNotQueued option to MqttClient

README.md
The number of parameters for mqtt.Client#unsubscribe was wrong in the documentation. Unsubscribe method doesn't accept an options parameter.
=> Removed [options] param from mqtt.Client#unsubscribe

lib/connect/index.js
This change allows a browserified application to use the MqttClient exported by mqtt.js.
=> Export MqttClient from lib/connect/index.js to support browserization

lib/client.js
This PR addresses the following error:
```text
project/node_modules/mqtt/lib/client.js:828
origSubs = original.subscriptions,
^
TypeError: Cannot read property 'subscriptions' of undefined
at project/node_modules/mqtt/lib/client.js:828:30
at Store.del (project/node_modules/mqtt/lib/store.js:78:5)
at MqttClient._handleAck (project/node_modules/mqtt/lib/client.js:826:26)
at MqttClient._handlePacket (project/node_modules/mqtt/lib/client.js:279:12)
at process (project/node_modules/mqtt/lib/client.js:230:12)
at Writable.writable._write (project/node_modules/mqtt/lib/client.js:240:5)
at doWrite (project/node_modules/readable-stream/lib/_stream_writable.js:237:10)
at writeOrBuffer (project/node_modules/readable-stream/lib/_stream_writable.js:227:5)
at Writable.write …
```
=> Fixed an error in handling outgoingStore.del

test/client.js
A test was singled out when developing a previous commit. Restore the unit tests to normal operation.
=> Remove a .only on a test.

bin/pub.js
`mqtt publish topic 0` should publish "0" instead of "". But `mqtt publish topic -m 0` behaves as expected.
=> Set default message (bin/pub) as empty string in minimist's config object

lib/connect/ws.js
As discussed.
Note: The test framework isn't set up to test this, e.g. by mocking websocket-stream, so I've omitted tests for this minor fix, as extending the test framework is a bit out of scope.
=> Default to using port 443 for wss connections. Fixes #477

bin/pub.js, bin/sub.js
If the clientId is a number (OpenSensors.io does this), the minimist library will interpret it as a number, causing an error when the code goes to use it.
I've added clientId and its aliases to the 'string' types so things will continue to work.
Note that minimist explicitly requires you to spell out all the strings, it won't figure it out from the alias this. I've contact them but it appears the project maybe orphaned or at least not on the front burner. 
Also not that minimist doesn't take an 'integer' parameter so that could possible be removed from the dictionary passed to minimist. However, I did not make this change and its presence is harmless.
=> add clientId and aliases as 'string' types

lib/client.js, package.json, test/abstract_client.js, test/client.js, test/websocket_client.js
#460 #468 #469 #450 are about a subscribe that goes multiple times to AWS IoT.
I reverted your fixes @miotabbott because they were not working on my machine, and multiple duplicated subscribes where happening. I changed the queue logic, so only  PUBLISH packets are stored in the `outgoingStore`.
@miotabbott can you please review this? Also everybody else :).
=> Avoid storing subscribes in the outgoingStore

README.md
I wanted quickly check in documentation if this library support wildcard characters in subscribe function, unfortunately, I found this information in one of the issues (#432). 
This PR only clarify that library has support for MQTT wildcards.
=> Update documentation for subscribe function

package.json
Makes the `browser-build` NPM script ditch any platform-specific code by using cross-platform Node-based utilities.
Fixes #499
=> Use cross platform alternatives for browser-build

lib/connect/index.js
Current issue: #392 
When requesting the `mqtts` protocol in the browser `ws` is used instead of `wss`. I attempted to solve the issue with desired feedback in issue #392. 
Solution: Check if requesting a secure protocol then skip any insecure protocols in the filter. I chose this because it still relied on the filter. The `isSecure` constant is very clear. The only thing funny is the mod I used to determine if the key was secure. I'm open to suggestions but this passes all the tests and works with my code. I took a look at creating a test case, but I don't think I'm familiar enough with your setup to do that.
Alternative solutions:
- reversing protocolList
- if statement like proposed in issue
=> Use secure protocol when requested. 

README.md
Added it after the example so that it wasn't too high up. Also a link to what `async-await` is in case people didn't know about it.
=> Added note about async-mqtt

package.json
The published package has `"types"` specified in its `package.json`, but doesn't include them.
=> Publish types to NPM

types/lib/client.d.ts
When building with `noImplicitAny`, TypeScript complains that the argument of `streamBuilder` is implicitly typed as `any`, while it was meant to be typed as `MqttClient`.
=> Improve typing

types/lib/client.d.ts
fixes #571 
I think that the callback for the end functions should be explicitly defined as the same as the other callbacks.
=> Add a callback for the end function

README.md, lib/client.js, test/abstract_client.js
For a specific problem I require to mark a message as duplicate when publishing to a topic. With this change the flag can be added to the options when publishing messages.
=> Add duplicate flag to publish options

types/lib/client-options.d.ts
The same change as #603 should be also applied on the TypeScript definition.
=> Add duplicate flag to publish options on the TypeScript definition

lib/client.js, test/abstract_client.js
`QOS=0` packets are buffered in-memory if `queueQoSZero` as before, however `QOS>0` packets are persisted in Store to survive client process crash.
Fixes #607 
Fixes #398
=> Use Store for qos>0 packets

package.json
This should avoid some mistakes of coding styles on TypeScript definitions.
=> tslint should be run on pre-commit

lib/client.js, test/abstract_client.js
This handles the double subscription issue on server restarts. This usually happens when the client has a subscribe call inside the connect event, ex the CLI <a>https://github.com/mqttjs/MQTT.js/blob/master/bin/sub.js#L90-L102</a> 
I'm not sure if this is the best way to handle this and open to a better way!
=> Added checks for double subscription issue

lib/client.js
Hi, I just removed the `store.del` because at that moment the package is not in the `this._inflights` object in the store.js file and so another `missing packet` error is thrown. I think just skipping the package should be fine, my bad I haven't double checked in the previous bux fix.
=> Fixes #648

.gitignore, .jshintrc, README.md, lib/connect/index.js, lib/connect/wx.js, package.json, test/browser/wx.js, test/helpers/wx.js, test/mqtt.js, types/lib/client-options.d.ts
https://github.com/mqttjs/MQTT.js/pull/653#issuecomment-319734340
I open this pr because of the gt reports.
@mcollina , stragely, I forked again and did the same change, I got failed message when I run `npm run weapp-test` first time. and I run npm test twice, it worked with no exception I got yesterday.
anyway, I hope this pr will be merged soon. thank you for your patience.
=> add support for weapp

README.md, lib/client.js, test/abstract_client.js, types/lib/client-options.d.ts
This pull request implements a option `resubscribe` for controlling re-subscribe.
The default value of `resubscribe` is true. It doesn't break current behavior.
It will fix #664 partially. Partially means, if `suback` has error payload, then re-subscribe topics should be removed. It is a different issue.
=> Add a flag to control re-subscribe functionality.

lib/connect/tls.js, test/secure_client.js
=> Ignore path when connect as MQTTS.

test/abstract_client.js
In QoS2 sequence,
when the client receives `publish`, the messege is stored into
`incomingStore` and sends pack `pubrec`. Then the server sends `pubrel`
to the client. Finally,  the client calls `handleMessage` with stored
message. If no errors are hannpened, `pubcomp` will be sent, but any errors
are happened, `pubcomp` shouldn't be sent.
This test is for the error case, so I replaced the description.
=> Replace `pubrel` with `pubcomp`.

lib/connect/wx.js
On wechat, if the socket is closed, the socketOpen mark is not set to false , so you might send data before the websocket is opened, and the following codes will result in error:
```
function sendSocketMessage (msg) {
if (socketOpen) {
wx.sendSocketMessage({
data: msg
})
} else {
socketMsgQueue.push(msg)
}
}
```
BTW, why are we pushing msg into a msg queue when the socket is not opened? If we send some message to socket before mqtt connection is done, those messages will be send to server, will it result in error?
=> fix a bug that you can not reconnect on wechat

lib/client.js, test/mqtt.js
I am currently using a service that require clientId to be empty.
I modified the option to clientId to allow it to be "" and create a default when it is not `string`.
According to the spec, it should only be set empty along with clean session. 
I can add that part of checking if necessary.
=> add support to allow empty string clientId

examples/tls client/mqttclient.js
Added protocol ssl. Without protocol parameter this example doesn't work.
=> Updated tls client example

README.md, lib/client.js, lib/store.js, test/abstract_client.js, types/lib/client-options.d.ts, types/lib/client.d.ts
Store._inflights set to {} instead of null to prepare manual reconnect.
Deferred the timing of manual reconnect calling if reconnect() called
during disconnecting process.
NOTE: reconnect() function usually called from 'close' or 'error' handler.
=> Fixed resource management on manual reconnect.

README.md
I wrote a store for inflight messages using `localForage`. Linking it in docs may allow others to also benefit from it.
=> Add mqtt-localforage-store link

types/lib/client-options.d.ts, types/lib/types.d.ts
Remove unnecessary semicolons from some of the Typescript declaration files - mostly where there are nested objects and arrays in the interfaces.
Addresses issue #740
=> Remove unnecessary semicolons from TS declarations

package.json, test/mocha.opts
- uses `--exit` to hack around non-exiting process
* * *
This is a temporary fix for #703.
*Actual* fixes as [mentioned here](https://github.com/mqttjs/MQTT.js/issues/703#issuecomment-357872112) are another issue entirely.
=> update mocha to v4.x

lib/client.js, test/abstract_client.js
Hello,
This is mainly to be able to handle cleanly situations where the client has been misconfigured.
I've added a test showing the issue that I am experimenting.
It is also partly related to #710 although it does not require a forced end.
=> fix issue while ending a disconnected client

README.md
On line 49, I replaced 'id' by 'is'... that's it...
=> typo correction in README.md

README.md, lib/client.js, test/abstract_client.js
Here is the support for an `end` event #767.
The additional tests may sometime reproduce the bug fixed by #770.
=> end event added and tested

.gitignore, lib/client.js, test/client.js
When a pingresp does not occur, things are forced closed.  However, callbacks in the outgoing queue are not invoked.
Added code to the cleanup, so that in the case of forced argument of true, will invoke the callbacks with  an error.
Also fixed a few spelling errors.
=> Force callbacks when pingresp not received or when end called with true.

lib/connect/wx.js
As the weapp document mentioned [here](https://developers.weixin.qq.com/miniprogram/dev/api/api-network.html):
>域名不能使用 IP 地址或 localhost，且不能带端口号；
(The domain name cannot use the IP address or localhost, and cannot have the port number.)
We should not add port on the url, weapp will use default port 80 for `ws` and port 443 for `wss`.
In fact, we can only use these port for weapp client.
If we add port on the url, it will cause the error like this:
```
error: ws://api.xxx.com:80 不在以下 socket 合法域名列表中
(error: ws://api.xxx.com:80 not in socket legal domain name list)
```
And that's why this issue #729 happens.
=> Fixed #729: weapp url should not have the port number, remove it from weapp url builder

lib/connect/wx.js
As weapp doc [mentioned](https://developers.weixin.qq.com/miniprogram/dev/api/network-socket.html#wxsendsocketmessageobject),
`wx.sendSocketMessage` can only send data of type String or ArrayBuffer.
The `msg` got here will be type of TypedArray, which can be sent successfully in wechat devtool (browser environment), but failed in real device (not real browser envirment). 
This PR fix it.
=> Fixed: weapp's real device environment can only send data of type String/ArrayBuffer

lib/connect/wx.js
Directly remove weapp port number (#811) may be confused for people using a mqtt server listen on port like 1883 in development. 
Although they can only use port 80 or 443 in weapp, we should let weapp throw the error, rather than conceal it.
=> Update: weapp add port number back when not 80 or 443

lib/connect/index.js, test/client.js, types/lib/client-options.d.ts
Fixes #775 
- Note: Could in rare cases break poorly defined options.
```
servers:[{
host: getMQTTBrokerHostname(),
port: 8883,
protocol: 'wss'
},{
host: getMQTTBrokerHostname(),
port: 1884,
protocol: 'ws'
}]
```
I imagine this is the most common use case.
```
protocol: 'ws',
servers:[{
host: getMQTTBrokerHostname(),
port: 1884
}]
```
```
protocol: 'ws',
servers:[{
host: getMQTTBrokerHostname(),
port: 8883,
protocol: 'wss'
},{
host: getMQTTBrokerHostname(),
port: 1884
}]
```
This will not default the second attempt to the `ws`. The code will need to be refactor extensively in order to properly resolve protocols on a per attempt basis with a default. Alternatively the protocol for a server can be required instead of optional.
=> Use protocol from server list if available.

examples/tls client/mqttclient.js
=> Fixed invalid protocol definition in TLS client example.

lib/client.js
1: Set minimum of this.nextId initialisation to 1:
```
this.nextId = Math.max(1, Math.floor(Math.random() * 65535))
```
2. Missing slot 65536 is not the case, the previous function was the following:
```
var id = this.nextId++
// Ensure 16 bit unsigned int:
if (id === 65535) {
this.nextId = 1
}
return id
```
Which results into the following behaviour:
1. nextId is 65535
2. id becomes 65535
3. nextId becomes 65536
4. if(id === 65535) sets nextId to 1 while nextId is already 65536
It would be different with var id = ++this.nextId.
Nevertheless, it's  hard to read and not very explicit, id is a copy of nextId while nextId is changed which is not really clear (devil is here definitively in the detail) therefore I added a merge request to change the implementation to with the purpose of easier …
=> Solves issue #810

README.md
I have setup a small mqtt cluster with 2 nodes on Kubernetes. If I try to run your example I sometime miss the `Hello mqtt` message, and the sample app just keep running.
If I change the example by moving the publish inside the callback I always get the message and the app correctly close.
Can this be caused by the fact that the publish doesn't wait the subscribe to be sucesfully? Maybe I connect to another node of the cluster or some concurrency issue?
Or this can be an issue on my cluster?
Can you confirm that it is better to wait for the subscriber before sending the message? I know that this is probably a not real world scenario, but...
=> Improved example with subscribe callback.

lib/client.js, test/abstract_client.js
Even if reconnectPeriod is 0, client should resend publish/purel
packet when clean is false.
So I removed `that.options.reconnectPeriod > 0` guard condition from
the connect handler.
Added resend from pubrel functionality.
In the following scenario, resend message should be pubrel.
1. Client connects to the broker with clean session false.
2. Client publishes QoS 2 message.
3. Broker receives the message and send pubrec to the client.
4. Client receives the pubrec message and send pubrel to the broker.
5. Client disconnects from the broker.
6. Client reconnects to the broker.
7. Client receives connack from the broker.
8. Client should resend pubrel automatically.
When `_sendPacket()` is called, if the packet type is `pubrel` then
call `storeAndSend()` instead of `send`acket()`.
Added …
=> Fixed resend functionality.

lib/store.js, package.json, test/abstract_client.js
Added preserving publish order functionality to `Store` using `es6-map`.
`es6-map` can preserve insertion order.
If target environment is ES6, `es6-map` is native ES6 Map, otherwise use
fallback implementation that has the same interface as ES6 Map.
Updated some tests that depends on Store's internal structure (_inflights).
Added test to check publish order when reconnects.
=> Fixed #854.

lib/client.js, test/abstract_client.js
Emit `connect` event after processing of `outgoingStore` is completed.
Problem:
When client publish new message during proccessing of publish/pubrel messages in `outgoingStore`, the newly published message interrupts the process. As a result, messages are not sent by published time order.
Outcomes:
Above message order problem is fixed by this commit. Added unit test verifies this case.
=> Delayed emit timing of `connect` event.

README.md, lib/client.js, test/abstract_client.js, types/lib/client.d.ts
Added new callback `cbStorePut` to `publish()`. `cbStorePut` is called when message is put into `outgoingStore`.
Problem:
When disconnection occures right after `publish()` but `callback` is not called, then reconnect, client can't know if the message is completely stored into `outgoingStore`.
Outcome:
This commit fixes above problem.
Client can know that message has been put into `outgoingStore` when `cbStorePut` is called.
=> Add new callback called when message is put into `outgoingStore`.

README.md, lib/client.js, test/client.js
I fixed subscribe properties and docs for subscribe
=> fix properties mqtt 5 in subscribe

lib/client.js, test/abstract_client.js
I ran into an issue where my store was being filled with incoming QOS 2 messages, even though those messages had completed the QOS 2 handshake. If I understand the last point of `[MQTT-4.3.3-2]` in the MQTT spec correctly, the client should forget incoming QOS 2 messages once the `PUBCOMP` message has been sent.
@mcollina I noticed you also saw this issue when [you commented that this put should be a delete](https://github.com/mqttjs/MQTT.js/pull/416#discussion_r65729673). Do you know of any issues doing so could cause?
=> fix: delete completed incoming QOS 2 messages

lib/client.js, test/abstract_client.js
If `publish()` is called during stored packets processing, store the packet id into `packetIdsDuringStoreProcessing` kvs. The key is packet id and the value is boolean (true: prossesed, false: not processed). At this time, the value is false. If the packet is actually sent, the value is set to true.
When stream process reaches the end, check all of `packetIdsDuringStoreProcessing` are processed, if it doens't, try again flowing process from the beginning. In this process, already processed (but not removed yet because puback is not receieved) packets should be skipped. In order to do that, check  `packetIdsDuringStoreProcessing` value. If it is true, skip it.
=> Fix publish interrupt during stored packets processing.

lib/client.js, test/client.js
[Disconnect MQTT 5.0](https://docs.oasis-open.org/mqtt/mqtt/v5.0/cos02/mqtt-v5.0-cos02.html#_Toc1477505). Can be sent from server side.
=> server side disconnect handling

lib/client.js
This addresses the memory leak discussed in issue #791 
Alongside, it is more efficient as timer objects are created only if it's necessary.
=> perform nextTick work only if work needs to be done

README.md, lib/client.js, test/client.js
I don`t see any information about reconnections logic in spetification and I think that behavior more logical in this case. @mcollina, what so you think?
[Disconnect MQTT 5.0](https://docs.oasis-open.org/mqtt/mqtt/v5.0/cos02/mqtt-v5.0-cos02.html#_Toc1477505).
=> process disconnect packet w/o full destroy the connection

lib/client.js, test/abstract_client.js
Conditional flush `outgoing` on close.
Scenario:
1. The client connect to the server.
2. The client sends subscribe to the server.
3. The server destroys the client connection before suback sending.
4. The client detect `close` event, then reconnects to the server.
At the step4, `outgoing` still stored the callback for
subscribe. However, it has never called because server doen't send
corresponding suback.
The same thing happens on unsubscribe.
So I defined subscribe/unsubscribe as volatile.
The volatile type of `outgoing` entries should be cleared when `close`
from the server is detected.
On the contrary, QoS1 and QoS2 publish is not volatile. Because they are
resent after reconnection. And then, callback in the `store` is
called. This behavior shouldn't be changed.
So I added `volatile` …
=> Fixed #952.

lib/connect/tls.js, test/secure_client.js
Hey there,
I figured the best way to start this discussion was with a PR.
I have a scenario where I'm trying to talk to an MQTT broker that's behind a proxy. This proxy is performing SSL/TLS passthrough. Having read into [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) I discovered the `servername` option in the options for [tls.connect](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback).
I found that the only way to connect was by explicitly setting `servername` to the same value as `host` (the hostname for the proxy).
I'm wondering does it make any sense to set that as a default for convenience? Feel free to reject in any case 🙂
=> fix: set default servername in tls connect

test/secure_client.js, types/lib/client-options.d.ts
This PR addresses adding secureOptions to ISecureClientOptions. This addition gives the interface the ability to accept secureOptions for TLS, including TLS version enforcement and cipher suite lists.
MQTT over TLS does not currently support adding TLS secureOptions on connect, so this is a new that improves our ability to control security on the MQTT client..
=> feature: add secureOptions to ISecureClientOptions for TLS

.airtaprc.yml, .travis.yml, package.json, test/browser/server.js
Currently the support for zuul and ngrok are broken and npm install fails as a result. This removes those dependencies and upgrades our browser testing to airtap
=> refactor: remove depedency on zuul

lib/connect/tls.js, test/secure_client.js, test/server.js
=> feat: support SNI on TLS

.github/workflows/nodejs.yml, README.md
These are more minor doc fixes for the release of the v4 mqtt.js package
=> chore: change workflow to v10-14 and doc fixes

lib/client.js, test/client_mqtt5.js
There are a few historical PRs that I looked through related to this PR: https://github.com/mqttjs/MQTT.js/pull/771/files
https://github.com/mqttjs/MQTT.js/pull/827/files
This PR addresses some of the flakiness in tests seen in the build system, both by adding a minor adjustment to a test but more importantly by adjusting the way `end()` calls it's callbacks.
If the `end()` method is disconnecting, it will simply return and never invoke the callback passed to it... This seems like flawed behavior since the callback passed is unique to that call to `end()`. This PR changes how `end()` works, so that the callback is invoked regardless if the client is disconnecting or not. Additionally, it removes the use of arguments that was introduced in the above two PRs, as I could find no logical …
=> refactor: callbacks on end()

lib/client.js, lib/connect/index.js, lib/connect/tcp.js, lib/connect/tls.js, lib/connect/ws.js, test/abstract_client.js
there is a security vulnerability created by outputting the whole options object in the debugs. In order to not do this we replace the line for debug to multiple single lines accessing the important options values.
=> fix: better options debugging

.github/workflows/nodejs.yml
This is a minor change to the workflow that will add debug log output on the test runs. Currently when a flakey test fails there is no possible way to debug why it is happening, the error logs are not useful enough. So adding debug logs will fix some of this.
=> ci: add debug logs to tests

lib/connect/wx.js
Wechat mini app document url:
https://developers.weixin.qq.com/miniprogram/dev/api/network/websocket/wx.connectSocket.html.
If the protocols value is 'mqtt' instead of ['mqtt'], it will be failed if
you use the android device, the interesting thing is iOS works.
Both android and ios works if the value is an array.
=> The protocols parameter of wx.connectSocket should be Array.

package.json
The `debug` package is missing from dependencies resulting in an error being thrown:
```
internal/modules/cjs/loader.js:965
throw err;
^
Error: Cannot find module 'debug'
Require stack:
- /app/node_modules/mqtt/lib/client.js
- /app/node_modules/mqtt/mqtt.js
```
=> Add missing `debug` dependency

types/lib/client-options.d.ts
The `payloadFormatIndicator` in the README defines the boolean type https://github.com/mqttjs/MQTT.js/#mqttclientstreambuilder-options
=> fix: fix payloadFormatIndicator to boolean type

lib/connect/index.js, lib/connect/ws.js
currently webpack based projects couldn't import mqtt.js because incorrect browser detection.
It's not a problem for react, where node-shims enabled, but a pain for angular (where enabling node-shims isn't supported officially)
To fix that issue we need to check if `process` exists (it will be not available in browser)
Also due to shims in webpack we need to check are we in process of bundling, or not.
=> correct browser detection

lib/client.js, lib/connect/wx.js, lib/store.js
if we do not add shims to browser `process.nextTick` does not exist, because of missing `process`.
In v8 eventloop sequence is:
```javascript
process.nextTick(callback) // runs first, after current Tick
setTimeout(callback, 0) // runs after nextTick
setImmediate(callback) // runs after all (https://github.com/nodejs/node-v0.x-archive/issues/25788#issuecomment-128869483)
```
That's why where is possible (in destructors) process.nextTick substituted with setTimeout.
Where it's significant - substitution will be done if process.nextTick is missing.
=> do not use process.nextTick without check that it exists

README.md
change some inconsitent variable names in docs
=> docs consistency

examples/wss/client_with_proxy.js, lib/connect/index.js, lib/connect/ws.js, test/browser/test.js, test/mqtt.js
This fixes https://github.com/mqttjs/MQTT.js/issues/1130 by replacing url.parse by the URL class as advised by the [Node documentation](https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost) on the subject:
```quote
Use of the legacy url.parse() method is discouraged. Users should use the WHATWG URL API. Because the url.parse() method 
uses a lenient, non-standard algorithm for parsing URL strings, security issues can be introduced. Specifically, issues with host 
name spoofing and incorrect handling of usernames and passwords have been identified.
```
Kind regards,
Hans
=> Replace url parse by url class

lib/connect/index.js
this is to fix the regression published in v4.2.3
=> fix(ws): add all parts of object to opts

lib/connect/index.js
Since 70a247c changed how we generate options, we now end up sending an empty username and password when they are not set, instead of sending _no_ username and password. This ends up confusing some MQTT servers, which don't properly detect an empty username/password as an anonymous login.
This can be seen most clearly in the connect flags:
```
Connect Flags: 0x02, QoS Level: At most once delivery (Fire and Forget), Clean Session Flag
0... .... = User Name Flag: Not set
.0.. .... = Password Flag: Not set
..0. .... = Will Retain: Not set
...0 0... = QoS Level: At most once delivery (Fire and Forget) (0)
.... .0.. = Will Flag: Not set
.... ..1. = Clean Session Flag: Set
.... ...0 = (Reserved): Not set
```
```
Connect Flags: 0xc2, User Name Flag, Password Flag, QoS Level: At most once …
```
=> Don't send empty username and password

examples/wss/client_with_proxy.js, lib/connect/index.js, test/browser/test.js, test/mqtt.js
The changes introduced in a previous PR are being rolled back due to detrimental affects on users.
=> fix: rollback URL

package.json
'duplexify' is used by MQTT.js but not present in package.json
- https://github.com/mqttjs/MQTT.js/blob/37b12cb9/lib/connect/ali.js#L4
- https://github.com/mqttjs/MQTT.js/blob/37b12cb9/lib/connect/wx.js#L4
- https://github.com/mqttjs/MQTT.js/blob/37b12cb9/lib/connect/ws.js#L5
- https://github.com/mqttjs/MQTT.js/issues/1215
=> Add missing 'duplexify' dependency

package.json, types/index.d.ts, types/lib/client-options.d.ts, types/lib/client.d.ts
userProperties changed from being object to being {[index: string]: string[]} (name-value string pairs)
fixes #1248
Not all tests are passing, but same test fail as on Master
=> Improved TypeScript declarations for userProperties

test/abstract_client.js, test/client.js, test/client_mqtt5.js, test/server_helpers_for_client_tests.js, test/websocket_client.js
I found an issue in test case where the wrong connection protocol was applied.
The test cases of abstract_client.js are designed for using multiple protocols (mqtt, mqtts, and ws).
However some of test cases used mqtt explicitly. So the test cases use only mqtt protocol three times instead of the combination of mqtt, mqtts, and ws.
It should be tested by mqtt, mqtts, and ws.
Send a PR with the following modifications.
- Added code to create a broker for Secure(TLS)
- Added code to create a broker for WebSockets
- Moved MqttServerNoWait to test/ websocket_client.js
Fixed client creation.
__Before__
```js
client = mqtt.connect({
```
__After__
```js
client = connect({
```
Fixed broker creation. 
__Before__
```js
var server2 = new MqttServer(function (serverClient) {
```
__After__
```js
var …
```
=> fix multi protocol test mechanism.

README.md
Myself and other users have run into problems trying to use the browserify directions with non ww/www urls.
See #1202 
I also went to the effort to figure out how to minify the output, cutting the output size by over 66%
I also changed the directions to show how to create the browser build from scratch rather than from another project
tree with mqtt.js already installee.
Hopefully these help!
=> 66% smaller browserify output. cut dependencies. ws/wss warning for newbies

README.md
Firstly: I love this module, it's really helpful and I use it all the time.
I was using this module with TypeScript for the first time today and found the docs a bit confusing. I made these changes because I would have liked to have had this information up front and labelled more clearly:
* How to import the contents of MQTT.js in more than one import style
* A TypeScript example showing off one of the types in MQTT.js
I also added the WeChat and AliPay protocols to the list of the supported protocols because I thought it was a bit weird that they were listed in their own section but not there, and restructured the section to only contain one example of the specific usage to make it clearer what's different there.
Thank you! 😄
=> Rework examples to be a bit more specific

types/lib/client-options.d.ts
Type signatures and implementations are inconsistent.
topicAlias should be number type, and payloadFormatIndicator should be boolean type.
relative resource:
* Implement: https://github.com/mqttjs/MQTT.js/pull/1301/commits
* Problem: https://github.com/mqttjs/MQTT.js/issues/1357
* Same issue: https://github.com/mqttjs/MQTT.js/issues/1334
=> fix(type): fix push properties types

package.json
Version 8 is a stub, because in v8 types are integrated in the main package.
=> fix(typescript): Use correct version of @types/ws

lib/connect/tls.js
This avoids showing a warning when the broker address is just an IP
[DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
Same fix as node-postgres has used https://github.com/brianc/node-postgres/pull/1890/commits/d3c8ebac78347ee3bd21f3734cd05ae9acf5762a
=> Skip TLS SNI if host is IP address

types/lib/client-options.d.ts
This Pull Request adds support for ALPN.  
With this change it is now possible to use AWS MQTT Broker on Port 443 with Custom Authorization.  
More information at: https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html  
This change is not AWS specific, there's more use cases behind the support of this feature.  
For more references have a look at the NodeJS types repository: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/tls.d.ts#L446
Example:  
```
mqtt.connect("AWS_ACCOUNT_ID-ats.iot.eu-west-1.amazonaws.com", {
...
port: 443,
ALPNProtocols = ['mqtt']
...
})
```
=> Add support for ALPN TLS extension

package.json
Since number-allocator https://www.npmjs.com/package/number-allocator
1.0.9, js-sdsl https://www.npmjs.com/package/js-sdsl is used insteaad of
collections https://www.npmjs.com/package/collections.
collections modify intrinsic type such as Array, it has unexpected side
effect for users. So I removed the dependency of collections.
It is a partial fix for #1392.
Replacement for LRU map is still needed to remove collections dependency.
=> Removed collections.js dependency from number-allocator.

lib/client.js
Fix a regression introduced by #1301.  The `cb = cb || nop` line in `_sendPacket` was adding a callback where none existed before.  This changed the behavior of `sendPacket` (without the underscore) by adding a listener to the `drain` event, and you can quickly overflow the max # of listeners if you're trying to publish faster than the stream will allow.
=> fix drain leak

types/lib/connect/index.d.ts
This makes it so that it makes it more readily apparent that you can omit the URL string, and provide the options as the first parameter instead.
This change purely effects the typing in order to make it better represent the underlying code, so it shouldn't cause any breaking changes.
=> Fix the typings for the connect function to have the proper overloads

README.md
I'm putting my efforts on MQTT.js vNext on hold, so removing the reference to it from the README.
@YoDaMa @BertKleewein @anthonyvercolano @ryanwinter
=> Remove reference to vNext from README

package-lock.json, package.json
Reproduce failing test: 
```
npx mocha -g "should not resubscribe when reconnecting if suback is error" test/client.js
```
Seems the same happens with mqtt-packet@7
Error
```
1) MqttClient
auto reconnect
should not resubscribe when reconnecting if suback is error:
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (MQTT.js/test/client.js)
at listOnTimeout (node:internal/timers:557:17)
at processTimers (node:internal/timers:500:7)
```
@YoDaMa any hints?
=> chore: bump mqtt-packet@8.1.1

lib/client.js, test/abstract_client.js
We've been using this library extensively in a project that makes a *lot* of subscriptions and have noticed that it's been leaking memory (which is causing NodeJS to crash with "JavaScript heap out of memory"). 
We've pinpointed this to the MQTT.js library's "message id to subscription" mapping:
A message ID is assigned and stored in `messageIdToTopic` whenever a new subscription is started and resubscription is enabled (which is the default).  The message-id to topic mapping is never cleared and keeps accumulating over time, which creates a memory leak that can not be resolved by the caller. 
This mapping seems to have been introduced as a way to prevent resubscriptions of topics that have failed to subscribe on their first attempt, as introduced in as part of …
=> Fix memory leak in subscription "message-id to topic" mapping

types/lib/client-options.d.ts
* Adds typescript entries for the two top-level topic alias controls in client config: autoUseTopicAlias and autoAssignTopicAlias
* Modifies password entry to properly reflect the fact that password is, by specification, binary data (https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901072).  Leave string in for backwards compatibility.
=> fix(types): topic alias controls and password

lib/client.js
It looks the `topicAliasMaximum` is under the wrong object.
This seems to be affecting https://github.com/emqx/MQTTX
=> fix: topicAliasMaximum under must be under Connect properties

types/lib/client.d.ts
The callback that can be passed to client.subscribe can be invoked with null as observed in link below, https://github.com/mqttjs/MQTT.js/blob/b3ce3da84147c86eb176759f53fa929e96de7969/lib/client.js#L784
The type of the callback does not reflect this and assumes an error is always present. This patch fixes this.
=> fix(types): missing null declaration for error in subscription callback

package-lock.json, package.json
Fixes #1552
```bash
browserify 16.5.2 (main branch)
734K mqtt.js
306K mqtt.min.js
browserify 17.0.0
734K mqtt.js
305K mqtt.min.js
```
=> Update browserify, add missing client.off method to mqtt.min.js

.github/workflows/release-it.yml, .github/workflows/semantic-pr.yml, .gitignore, CHANGELOG.OLD.md, CHANGELOG.md, DEVELOPMENT.md, package-lock.json, package.json
This PR adds release-it module to handle releases and semantic PR title checks to improve changelogs.
Mind that in order to make the `release-it` action to work `NPM_TOKEN` secret must be created
Anyway a script `release` has been added to `package.json` that can be used to create releases interactively (much better then doing them manually like we do now)
In order to prevent overriding changelog, the old changelog has been renamed to `CHANGELOG.old.md`
I also did an `npm audit fix` that fixed 6 high security vulnerabilities
=> chore: release-it and semantic pr title

.github/workflows/mqttjs-test.yml, .github/workflows/release-it.yml, package-lock.json, package.json
BREAKING CHANGE: Dropped support for NodeJS 12-14
=> chore!: drop support for node 12-14

README.md
Also did a quick lint fix on readme
=> docs: add mqtt 5 beta banner and sponsors section

lib/client.js
This PR makes sure that new messages get published after a local store that accumulated some messages while the broker was offline, reconnects. In storeDeliver, this._storeProcessing got set to true before the check if there are actually stored packets left to send. So if there aren't any, this._storeProcessing will still be true on the next publish(), resulting in packets accumulating in this._storeProcessingQueue, but their invokes are never called, because Readable Event 'end' has already happened for the emptied Store and no new messages will be put into the Store as well. 
Fixes #1116
=> fix: `_storeProcessing` staying true after outStore got emptied

lib/client.js
By looking at the code I found that in some anonimous functions both `this` and `that` were used. Giving that this happens on events listeners both works but it would be better to only use one for consistency
=> fix: consistency, used `this` instead of `that`

.github/workflows/release-it.yml
I have created an organization secret named `GH_TOKEN` with a fine grained organization token to be used in release workflow. It has restricted access only to this organization repo with `content` permissions (create releases and push commits).
This should allow the release workflow to successfully create the releases and bypass the main branch restrictions when pushing commits directly on main branch (`chore(release): xxx` commit)
=> chore: use new `GH_TOKEN` secret

types/lib/client-options.d.ts, types/lib/client.d.ts
TypeScript definition of subscribe() has two functions.
https://github.com/mqttjs/MQTT.js/blob/aa49aaf9856fe9f433005e850b490a96505add19/types/lib/client.d.ts#L165-L167
The type of the  first parameter is string or string[].
The second parameter is opts. opts could have properties. e.g.)SubscriptionIdentifier
https://github.com/mqttjs/MQTT.js/blob/aa49aaf9856fe9f433005e850b490a96505add19/types/lib/client.d.ts#L168-L171
The type of the first parameter is string, string[], or ISubscriptionMap.
ISubscriptionMap is defined as follows:
https://github.com/mqttjs/MQTT.js/blob/aa49aaf9856fe9f433005e850b490a96505add19/types/lib/client.d.ts#L57-L67
MQTT spec defines properties are in common for all subscription entries on one subscription.
So ISubscriptionMap doesn't have properties.
When …
=> fix(types): subscribe definition

lib/client.js, lib/store.js, test/abstract_client.js
User callback is executed twice if the received PUBACK indicates failure (by reason code). 
Related issue: #1511
The following modification prevents the callback from invoked twice.
- If ``resonCode`` in PUBACK to failure, set the cb variable to NULL after the callback is invoked.
- When deleting a message from the store, do not invoke the callback if cb is null
=> fix: problem with publish callback invoked twice

README.md, lib/client.js, lib/handlers/ack.js, lib/handlers/auth.js, lib/handlers/connack.js, lib/handlers/index.js, lib/handlers/publish.js, lib/handlers/pubrel.js, test/abstract_client.js, test/browser/test.js, test/client_mqtt5.js, types/lib/client-options.d.ts, types/lib/client.d.ts
- Created `client.log` function that by default uses `debug` but can be overriden using `options.log`
- Created `client.nop`
- Moved all `client._handle` in `lib/handlers`
- Create `MqttClient.defaultId` static method
- Ensure shiftPingInterval is called every time a packet is written to the stream. Could fix #1257. An alternative could also to shift the ping interval every time a pingresp is received from server
=> refactor: move handlers to lib/handlers

src/lib/connect/wx.ts
When developing a project with WeChat mini program, I want to execute some tasks after disconnecting from the MQTT connection, but I found that the callbacks for close and end are not executed properly. This bug only occurs in the WeChat mini program.
=> fix: close and end callbacks not executed in the WeChat mini program

package-lock.json, package.json
The types that are exported for this project use types from `readable-stream` and `ws`, so those types need to be included as proper dependencies that get shipped to consumers. This PR moves those dependencies out of the dev block, and also bumps the Node types to make sure they work with the latest additions to the `readable-stream` types (i.e. using `asyncDispose`).
This ought to fix #1673 (it does for one of my project seeing the same error as that issue).
One downside of this is that consuming projects will need to be on a fairly recent version of `@types/node`, but I don't think that's the worst thing vs. not working at all for TS projects right now.
=> fix: move exported types out of dev dependencies

README.md
specify the Client as an event emitter to improve understandability
this PR aims to reduce issues such as: #756
=> docs(readme): specify the Client as an event emitter to 

README.md
**Title:** Document ALPNProtocols Option for Enhanced TLS Support
**Description:**
This PR adds documentation for the `ALPNProtocols` option in MQTT.js, enhancing clarity for users who wish to utilize multiple TLS protocols on the same port.
**Rationale:**
We've observed that many users were uncertain about how to correctly configure multiple TLS protocols, such as MQTTS and MQTT over WSS, on the same port. While MQTT.js inherently supports this through the `ALPNProtocols` option, it wasn't clearly documented. This omission can lead to confusion and potential misconfiguration.
By clearly detailing the `ALPNProtocols` option, we aim to provide clearer guidance, reduce user uncertainty, and ensure users can fully leverage the library's capabilities without hassle.
=> docs(readme): update with ALPNProtocols for supporting multiple TLS protocols

src/lib/client.ts
This is my first pullrequest, did I do everything correct?
Do I need to extend the documentation or something?
I dont know what branch to set as target, please feel free to change the target to a "correct" branch.
=> fix: set default value false for reconnecting in constructor (#1674)

README.md
* Clarifies the `connectAsync` function documentation to explain how the promise is resolved or rejected, and why the `manualConnect` option cannot work.
=> docs: Clarify the mechanism behind `connectAsync` (#1661)

package.json, src/lib/client.ts, test/abstract_client.ts, test/client_mqtt5.ts
Fixes some of the issues mentioned in #1686.
In particular:
1) exporting missing types from callbacks
3) missing callback argument
I tried to figure out how to fix 2) and 3) (inconsistent error argument declaration in callbacks and runtime/typing mismatch) but it goes deeper into the library (writing to streams) than I am comfortable with.
Maybe it is easier than I think, but I believe it needs some more overview of the project than I have.
=> fix: publish/subscribe/unsubscribe types and missing types exports

README.md, src/lib/client.ts, src/lib/connect/ws.ts, test/websocket_client.ts
We need to add special protocols to connect to our mqtt broker over websocket. With this small addition (which hopefully helps others as well) we can do it very easy. Otherwhise we need to build our own streamBuilder and copy alot code.
=> feat: custom websocket support

src/lib/shared.ts
node_modules/mqtt/build/lib/shared.d.ts:3:13 - error TS1259: Module '"stream"' can only be default-imported using the 'esModuleInterop' flag
3 import type internal from 'stream';
~~~~~~~~
node_modules/@types/node/stream.d.ts:1726:5
1726     export = internal;
~~~~~~~~~~~~~~~~~~
This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
Found 1 error in node_modules/mqtt/build/lib/shared.d.ts:3
=> fix: import type error

.eslintrc.js, src/lib/is-browser.ts
=> fix: detect web worker

src/lib/is-browser.ts
RN [support Websocket](https://reactnative.dev/docs/network#websocket-support), better to use it directly.
**Sample code for detecting is React native:** 
https://snack.expo.dev/-QQjqDN-8
Discussion: 
- [navigator.product ](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/product)is removed from modern web standard
- React native is not a browser, should we put it in `isBrowser` function?
=> fix: crash with React Native

.airtap.yml, README.md, examples/vite-example/src/App.vue, package-lock.json, package.json, test/browser/test.js
Users will be able to use `import mqtt from 'mqtt'` directly without using `/dist` imports
Fixes #1733
=> fix: make `import mqtt from 'mqtt'` work in browsers

src/lib/is-browser.ts
This pull request addresses the issue outlined in [#1743](https://github.com/mqttjs/MQTT.js/issues/1743), where the environment detection in the `is-browser` utility needed refinement. The changes improve the accuracy of environment detection across standard browser environments, Web Workers, and React Native environments.
=> fix: improve environment detection in is-browser utility

src/lib/PingTimer.ts, src/lib/is-browser.ts, test/browser/test.js, test/browser/worker.js, web-test-runner.config.mjs
=> fix: don't use worker timers in worker and add web worker tests

lib/client.js
Backport to version that supports NodeJS 14
As discussed in https://github.com/mqttjs/MQTT.js/issues/1756
Here is a backport of the #1752 fix to the v4 codebase
=> Backport #1752

src/lib/client.ts
`defaultConnectOptions.keepalive = 60` in `client.ts`
=> fix: typo in `client.ts`

src/mqtt.ts, test/abstract_client.ts, test/browser/test.js, test/browser/worker.js
=> fix: add keepalive test in webworker

src/lib/BufferedDuplex.ts
=> fix(browser): force closing client doesn't destroy websocket correctly

src/lib/BufferedDuplex.ts, src/lib/get-timer.ts, src/lib/is-browser.ts, src/lib/shared.ts
**located**: src/lib/client.ts
**method**: _setupPingTimer
**class**: PingTimer
**init**: getTimer(variant) = getTimer('auto')
The error is caused for the library `worker-timers` when the class `PingTimer` call `getTimer('auto')` method. This method `getTimer` doesn't recognize it's executed in ReactNative (RN), it know it's executed in a browser, but RN implements its own timers as: `setTimeOut`, `setInterval`, etc., when is called the method `workerTimer` instead `nativeTimer` the library `worker-timers` that implement `Blob` to store data or whatever it does, throw the next error: **[Error: cannot create URL for blob!]**, `Blob` it isn't supported by RN.
To support ReactNative (RN) it's necessary install 2 package additionals to RN projects:
- …
=> fix(react-native): error Cannot create URL for blob

package-lock.json, src/lib/PingTimer.ts, src/lib/client.ts, test/pingTimer.ts
=> fix: possible race condition in ping timer

package-lock.json, src/lib/connect/index.ts
Fix: process.nextTick is not a function (it is undefined) - error in react native apps,
which has been discussed in [React Native Support](https://github.com/mqttjs/MQTT.js/discussions/1841) topic.
=> fix(react-native): process.nextTick is not a function error

example.ts, src/lib/client.ts, src/lib/handlers/index.ts, test/abstract_client.ts
Actually keepalive is shifted every time a packet is written to stream. This is wrong as this doesn't mean the stream is up and in cases where there is a constant publish the keepalive never triggers as is keeps being shifted without closing the client.
With this PR we ensure that the keep alive timer is shifted only when we receive control packets as defined in specs: https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Ref363645900
Fixes #1727
=> fix: keepalive issues

src/lib/is-browser.ts
In the electron context without context isolation all protocols work like in node.
This is tested in the main as well as in the render context.
This PR evolved from that discussion: https://github.com/mqttjs/MQTT.js/discussions/1854#discussion-6585043
=> fix(electron): detect electron context

src/lib/connect/index.ts, test/mqtt.ts
=> fix: prevent url.parse to set `path` option

DEVELOPMENT.md, src/lib/handlers/ack.ts, test/abstract_client.ts, test/client_mqtt5.ts, test/runTests.ts
- Add error handling for failed suback requests
- specified constant the suback return code value
- copied error object used in other packet handlers, adjusted for this packet
- added error callback method used in other packet handlers
- passed error object to the callback method
Now the error creates the expected Exception with detail and is available from all error callbacks, consistent with the rest of the library.
```
error: Error: Subscribe error: Not authorized
at handleAck (/Users/tsteinholz/Development/MQTT.js/build/lib/handlers/ack.js:102:27)
at handle (/Users/tsteinholz/Development/MQTT.js/build/lib/handlers/index.js:36:31)
at work (/Users/tsteinholz/Development/MQTT.js/build/lib/client.js:221:40)
at writable._write (/Users/tsteinholz/Development/MQTT.js/build/lib/client.js:246:1 …
```
=> fix: suback Error Codes Handling

src/lib/is-browser.ts
[txiki.js](https://github.com/saghul/txiki.js) is a small JavaScript runtime compatible with most of the browser api; very nice for small embedded devices.
However, `MQTT.js` wrongly assume a `Node.js` compatibility because there is no `document` variable in the global space. Although, if it was using the browser ws, the lib would be compatible with it.
After discussion https://github.com/saghul/txiki.js/issues/557 with the creator of `txiki.js`, we both think that it should be the job to add the compatibility.
That's what I've added in the present PR.
Small remark, I also think that, in the future, it may be good to revisit the way `MQTT.js` determine if it can use native websocket or `Node.js` one through the `ws` module. Like checking if `WebSocket` exists in the global space, instead …
=> feat: add compatibility with txiki.js

README.md, src/lib/KeepaliveManager.ts, src/lib/client.ts, src/mqtt.ts, test/keepaliveManager.ts
I was testing the library with react native on an Android and an iOS device. I found out that the timers dont work in background on [Android devices](https://stackoverflow.com/questions/51997866/react-native-setinterval-getting-paused-when-app-is-in-background). On iOS everything seems to be ok.
With this PR we allow users to pass any timer solution. In my case I want to use https://github.com/ocetnik/react-native-background-timer which is working when app is in background too.
#1257 
#1577
=> feat: allow to pass custom timer for keepalive manager

src/lib/client.ts, src/lib/handlers/index.ts, test/abstract_client.ts
=> fix: reschedule pings problem

test/abstract_client.ts
Fixes (https://github.com/mqttjs/MQTT.js/issues/1897#issuecomment-2231365999).
When you try to execute the tests maybe one of them will fail because it hanged up and never ends. This PR fix that bug in almost all cases.
=> fix: tets hang up

src/lib/client.ts, src/lib/handlers/ack.ts, test/abstract_client.ts, test/helpers/TeardownHelper.ts, test/helpers/clean_method.ts
Improve the logic of close open connections when you instance a `serverBuilder` class or open a new connection using `client`. Call method `assert` interrupts the test and the method `after` will never called generating that the connections haven't closed yet will still open and other unit test will throw a error like `Error: listen EADDRINUSE: address already in use`.
This PR also remove the temp folders and files generated by this [`test`](https://github.com/mqttjs/MQTT.js/blob/2da3b3401db1bb880801c7264a2a51dc08d50f62/test/abstract_client.ts#L717) when failed.
=> fix(test): close open connections

src/lib/client.ts
https://github.com/mqttjs/MQTT.js/issues/1920
Potential concern: while this change is "accurate", there may be a backwards compatibility concern if someone is explicitly using the incorrect existing typing.  This would create a build-time error but would also notify the developer that the subscribe-related fields are useless.
=> fix(types): unsubscribe options type

README.md
The return types for `subscribeAsync` und `publishAsync` where not up to date.
Closes #1788
=> docs: update documentation for publish and subscribe

README.md
The EventEmitter link https://nodejs.org/en/learn/the-nodejs-event-emitter/ in the Client docs is not working and the page could not be found.
Changed the link to the actual Node.js Learn Event Emitter URL https://nodejs.org/en/learn/asynchronous-work/the-nodejs-event-emitter
=> docs: update Node.js Learn Event Emitter link

package-lock.json, package.json
=> fix(browser): bump readable-stream@4.7.0 to fix BigInt issues

src/lib/connect/index.ts, test/node/mqtt.ts
With this [commit](https://github.com/mqttjs/MQTT.js/commit/1004c78db7d6763f21c98fa3db2f12e688ca33ff) the removal of the “:”, for the protocol passed in connect options, was moved before the merge of parsedOptions.
```
parsedOptions.protocol = parsedOptions.protocol?.replace(
/:$/,
'',
) as MqttProtocol
opts = { ...parsedOptions, ...opts }
```
Previously, if someone passed as a protocol “mqtts:” (Protocol returned by the [URL interface](https://developer.mozilla.org/en-US/docs/Web/API/URL/protocol)) this was “cleaned” by removing the “:”.
By moving the replace after the options merge, a backward compatibility is maintained for those, like me, who find themselves having to update deps in codes where the protocol was passed in by taking the value from the URL interface.
I know that the …
=> fix: move protocol "clean" after merge of parsedOptions

electron-test/forge.config.js, electron-test/package-lock.json, electron-test/package.json, electron-test/wdio.conf.ts
This PR fix the error of chromdriver when it attempts to start a new session in browser.
=> fix(electron-test): webdriver session not created

README.md, esbuild.js, package-lock.json, package.json, src/lib/client.ts, src/lib/connect/index.ts, src/lib/connect/socks.ts, src/lib/connect/tcp.ts, src/lib/connect/tls.ts, test/node/socks.ts
This PR adds support for establishing TCP and TLS connections through a SOCKS proxy. Proxy support is enabled with a new `socks` configuration parameter that takes a curl-style SOCKS URL, or by setting an environment variable (`MQTTJS_SOCKS_PROXY`).
Supported schemes (and protocols) are `socks5://` , `socks5h://` , `socks4://` and  `socks4a://` .
=> feat: add intrinsic support for SOCKS proxies

package-lock.json, package.json
This PR resolves #1985:
- Removes the unused `reinterval` dependency.
- Moves `@types/ws` to `devDependencies` from `dependencies`.
- Moves `@types/readable-stream` to `devDependencies` from `dependencies`.
=> fix(deps): removed unused 'reinterval' dependency and move two @type/ dependencies to devDependencies.

package.json
Ref [#1983](https://github.com/mqttjs/MQTT.js/issues/1983)
This PR introduces a small change to the `package.json` file, adding a new export field for React Native compatibility.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R40): Added the `"react-native"` export field pointing to `./dist/mqtt.esm.js` to support React Native environments.
=> feat(exports): add react-native entry point to package.json
