- examples/client/secure-client.js
- examples/client/simple-both.js
- examples/client/simple-publish.js
- examples/client/simple-subscribe.js
- examples/tls client/mqttclient.js
Replace deprecated createClient method in examples with new connect method.
> Fix examples using deprecated method

- lib/connect/index.js
- test/mqtt.js
Signed-off-by: Octavian Ionescu <itavyg@gmail.com>
> added switch to secure protocol when crt and key are present

- lib/connect/ws.js
> Use port for protocol when none is provided

- .travis.yml
- bin/pub.js
- lib/client.js
This should be an easy fix, but please review anyway.
Also @yangpu can you please check if this solves your issue?
> Parse messages to the mqtt pub cli as strings.

- bin/pub.js
If this duplication is a mistake, please merge.
> Deleted duplicate code

- lib/client.js
Add proper management of stored messages to support persistent Store objects.
Changed stream reading mechanism to avoid overhead when reading stream.
Added reading condition to avoid reading all the stream in case a reconnection is taking place and is not done.
> outgoingStore reading stream modified (fix)

- README.md
- lib/client.js
- test/client.js
Adds a connect timeout, so that if the client is connected up until a certain timeout, the connection will be closed and another one will be created.
This is what I wanted to address in #286.
> Connect timeout

- lib/connect/ws.js
pass the option 'rejectUnauthorized' for self-sign certificate when using wss://URL
> pass the option 'rejectUnauthorized' for self-sign certificate when using wss://URL

- lib/client.js
- test/client.js
> Clear connackTimer before setting a new one

- README.md
- lib/client.js
- test/abstract_client.js
> Added force param to end()

- lib/client.js
- test/client.js
Hi,
after watching Matteo in many conferences about mqtt I decided to give it a try but I found a strange behavior when the client is offline.
So that's the case:
1) the client is offline and every second it tries to reconnect.
2) some messages are stored in the outgoingStore with qos 1 (no problem with qos 0 or 2).
3) after 30 minutes the client comes online again.
4) the first message in the outgoingStore is sent 1800 times (the other messages 1 time only). That happens because every time the client tries to reconnect it pushes the first message in the queue. 
So my solution is to fill the queue only when the client is actually connected.
> bad behavior when offline

- examples/wss/client.js
demo for connecting to server using wss
> wss Secure connection demo.

- .eslintrc
- .travis.yml
- package.json
- test/abstract_client.js
- test/abstract_store.js
- test/browser/server.js
- test/browser/test.js
- test/client.js
- test/helpers/server.js
- test/secure_client.js
- test/websocket_client.js
This adds a clean install for iojs v3, too.
@psorowka @sahilsk and everybody, please check :)
> Bumped websocket-stream to 2.0.2 and others.

- bin/pub.js
- bin/sub.js
> Allow key, cert, ca to be passed into cli. Don't break if no message is specified during pub.

- README.md
> Correct the clientId default value in README.md

- examples/tls client/mqttclient.js
> Fixes TLS Client example code.

- bin/pub.js
- bin/sub.js
Validate that the port is a number.
> Port validation.

- lib/client.js
- test/abstract_client.js
> ensure publish callbacks actually called after reconnecting

- package.json
> bump websocket-stream to 3.0.1 for nsp fix

- bin/pub.js
- doc/publish.txt
- package.json
As discussed in https://github.com/mqttjs/MQTT.js/issues/402
Examples: 
```
./bin/pub.js -t 'log-topic' -h localhost -sM
./bin/pub.js -t 'log-topic' -h localhost --stdin --multiline
```
> add --multiline to pub.js for message streaming via stdin

- README.md
- lib/client.js
- test/abstract_client.js
> Add publish event to mqtt.Client

- README.md
- lib/client.js
> Added mqtt.Client.isConnected()

- lib/connect/ws.js
- test/abstract_client.js
- test/websocket_client.js
> Use "mqtt" as WS protocol unless using v3

- lib/client.js
- lib/validations.js
- test/abstract_client.js
This is the PR addressing issue #172
> Modified subscribe() to validate topics before sending subscriptions to MQTT servers

- lib/connect/index.js
Just a small typo I saw while reading through the code.
Smallest pr ever 😄
> Fix typo in `Unknown protocol` error message

- lib/client.js
- test/abstract_client.js
fixes #453
Let me know what you think! I wasn't quite sure where to place this test, so I can move that if needed.
Thanks for this project! I've really enjoyed using it. 🌟
> ensure client.end() returns client even if called twice

- lib/connect/index.js
- test/mqtt.js
Should close https://github.com/mqttjs/MQTT.js/issues/464
> Missing protocol throws

- lib/client.js
- test/client.js
the stream can get flushed multiple times in parrallel otherwise.
> Stop flushing the stored messages stream when the connection dies,

- bin/pub.js
- bin/sub.js
This is not a parameter minimist recognizes.
And as per Matteo's request in #485
> remove 'integer' argument to minimist

- lib/connect/ws.js
The previous fix for #408 was incomplete.
> Use websocket protocol 'mqtt'. Fixes #487 and #408

- lib/validations.js
- test/abstract_client.js
> don't send empty sub list

- README.md
- examples/wss/client_with_proxy.js
- lib/connect/ws.js
dealing with websocket options by adding the key  wsOptions (like agent for proxys) to the standard options object.
maybe smarter then  
#511 
fix  #452 for (secure)websockets
> Ws options

- README.md
- lib/client.js
- test/client.js
> add a function to get last id

- .gitignore
- .travis.yml
- README.md
- ci/travis-test.sh
- lib/connect/ws.js
- package.json
- test/browser/server.js
- test/browser/test.js
- test/websocket_client.js
Testing Travis and saucelabs
Fixes #538 
Fixes #535 
Fixes #537
> Add transformWsUrl option, and fix some travis/browser test issues

- lib/client.js
- test/abstract_client.js
- test/client.js
Change resubscribe logic to resubscribe to topics on reconnect even if
the disconnect happened prior to the suback response.
Fix #555
> Resubscribe even if disconnect is before suback

- examples/wss/client.js
fix retain flag in publish, was 'retained' - typo
> fix retain flag in publish, was retained typo

- package.json
- test/websocket_client.js
> Bumped websocket-stream to 4.0.0.

- lib/client.js
- test/abstract_client.js
> Updated connack event to include the return code in case of errors.

- types/lib/client-options.d.ts
> fix type of some fileds in ISecureClientOptions

- lib/client.js
- test/client.js
Fixes #618.
@Shinjifei would you mind verifying that this solves your bug?
> Do not enqueue an unlimited amount of subscribes if disconnected

- README.md
> Link to mqtt-connection in place of the server example in the README

- .travis.yml
> Added node 8 to .travis.yml

- lib/client.js
- test/abstract_client.js
@tosone please verify if it solves your issues
Reported as: https://github.com/mqttjs/MQTT.js/commit/65852b5e294d5495f05a1f1a5b8fb46c64dcccf9#commitcomment-22397441
> Fixed regression introduced in #624.

- lib/client.js
- test/abstract_client.js
> the default value must be set for an empty options parameter

- types/lib/client-options.d.ts
- types/lib/client.d.ts
> TypeScript: QoS should be mandatory

- lib/client.js
- test/client.js
Hi @mcollina, I hope this solution can fix the bug.
> Fixes #415

- README.md
Correct some minor markdown formatting problems in the README file.
> Formatting corrections in README.md

- lib/connect/index.js
- test/mqtt_store.js
> Fixed #735.

- lib/client.js
- test/abstract_client.js
> Publish returns an error in the callback when store.put fails

- lib/client.js
- test/abstract_client.js
Here is the PR to fix the issue found here declared in this [comment](https://github.com/mqttjs/MQTT.js/issues/767#issuecomment-365211728).
I have also added a non regression test for this particular case.
Sorry for the mistake, my bad.
> Missing done check in _cleanUp

- test/abstract_store.js
> Added packet type (cmd) for existing replace test for store.

- lib/client.js
- test/abstract_client.js
Added asynchronous result callback function and error handling in
_handlePubrel similar to _handlePublish.
> Added error handling to imcomingStore.put callback in _handlePublish.

- lib/client.js
- test/abstract_client.js
- test/client.js
I fixed resubscribes after disconnect. MQTT 5 has packet specific settings(properties) and resubscribe must proccess with it settings.
> resubscribe mqtt5 fix

- test/typescript/broker-connect-subscribe-and-publish.ts
- types/lib/client-options.d.ts
Looking at mqtt-packet, 'will' payload should be a buffer
> fix various options definition for ts usage

- lib/connect/tls.js
> feat: SNI support

- README.md
- lib/client.js
- lib/connect/index.js
- lib/connect/tls.js
These are doc updates that improve readability. I won't keep this description long and say just look at the changes. 
All of these changes will be limited to markdown.
> docs: knick knacks here and there

- README.md
changes
- Add "About Reconnection" towards top of doc explaining transformWsUrl and other reconnection behavior.
https://github.com/mqttjs/MQTT.js/issues/1083
> Update reconnection docs.

- bin/mqtt.js
- mqtt.js
- package.json
This hasn't been fully verified but it should fix https://github.com/mqttjs/MQTT.js/issues/1008
> chore: move cli to bin directory

- package.json
Should fix https://github.com/mqttjs/MQTT.js/issues/1092
> chore: remove bloat from package

- bin/mqtt.js
This is a fix from PR #1096 , which moved some of the CLI functionality into the bin folder. 
We need to add some form of integration testing so this doesn't happen again...
Addresses: #1106
> fix: path for bin files

- README.md
> Add documentation for React

- lib/client.js
fixes: https://github.com/mqttjs/MQTT.js/issues/1152
> fix(client): reconnect bug

- package.json
#1154: fixes #1140, detecting if webpack is used (browser)
#1162: fixes #1152, reconnect bug
#1165: fixes #1160, add documentation for react
#1171: minor docs consistency improvements
> release(4.2.2): minor bug fixes

- lib/connect/index.js
> fix(secure): do not override password and username

- package.json
Addresses the production packages mentioned in #1287
> Fix production vulnerability

- package.json
This is a patch update to remove a security vulnerability from a old version of the package. As referred by #1306
> fix: security vulnerability in ws stream

- types/lib/client-options.d.ts
rollover of https://github.com/mqttjs/MQTT.js/pull/1369 to address linting issues
> fix(type): add properties type for IClientSubscribeOptions

- lib/client.js
- types/lib/client.d.ts
rollover of https://github.com/mqttjs/MQTT.js/pull/1231
> feat(client): auth handler for enhanced auth

- package.json
This solves https://github.com/montagejs/collections/issues/241
> Updated collections.js related package version.

- lib/client.js
Process is enqueued if messageId allocation is failure.
> Fix #1372.

- package-lock.json
- package.json
- src/client.ts
- src/write.ts
- test/test_connect.js
Sends CONNECT packet seemingly without errors, but times out receiving CONNACK. Need to investigate more.
> refactor connect

- package-lock.json
- src/client.ts
- src/utils/logger.ts
- src/utils/sleep.ts
- src/write.ts
- test/test_connect.js
Co-authored-by: Vishnu Reddy <vishnureddy17@users.noreply.github.com>
> fix: connect successfully

- package-lock.json
- package.json
- src/client.ts
- src/sequencer.ts
incorporating some of the feedback I had in #1449
> small tweaks

- README.md
- types/lib/client.d.ts
Also remove an unused import in types/lib/client.d.ts.
Fixes #1408
> docs: Update TypeScript docs to include installing @types/ws

- .github/workflows/stale.yml
Process the older issues first as these are the most stale, and also increase the operations / run so we can get through the backlog.
> process stale issues from oldest to newest and increase operations / run

- lib/connect/index.js
- lib/connect/ws.js
- lib/is-browser.js
Addresses issue https://github.com/mqttjs/MQTT.js/issues/1570
> fix: IS_BROWSER check is now safer and more agnostic about the bundler

- lib/client.js
- package-lock.json
- package.json
- test/abstract_client.js
The message restored from the store was written to the store again before sending.
The writing is a time-consuming process of updating the stored message.
Meanwhile, next message overtook.
The restored message was sent without being written to the store.
Added noStore flag to _sendStore function.
> fix: prevent store message on store when it's restored

- lib/client.js
> fix: setImmediate polyfill

- package.json
Please see: https://github.com/mqttjs/MQTT.js/issues/1639#issuecomment-1685898957
Fix #1680 
Fix #1639
> fix: export js file in dist folder (#1596)

- README.md
Fixed punctuation error in one of the sentences in README.md.
> docs: improve punctuation in README.md

- src/lib/TypedEmitter.ts
fixes the issue reported in https://github.com/mqttjs/MQTT.js/issues/1639#issuecomment-1771082000
> fix: add all `EventListener` methods to `TypedEventEmitter` interface

- esbuild.js
- examples/vite-example/package-lock.json
- examples/vite-example/package.json
- src/lib/client.ts
> fix: prop `window` is not defined in web worker

- src/lib/client.ts
> fix: leaked `close` listener in `startStreamProcess` loop

- package-lock.json
- package.json
Closes #1770 
I incremented in package json but should I also include package-lock.json?
Also, the tests were timing out when I ran them (also before I made changes)
> fix: increase help-me version to fix vulnerability in glob/inflight

- README.md
> docs: add protocol information in demo broker url

- package-lock.json
- package.json
This PR just updates worker-timers to fix #1802.
> fix: update worker-timers from 7.0.78 to 7.1.4

- src/lib/connect/tcp.ts
> fix: allow to use unix sockets in connect

- src/lib/handlers/index.ts
- test/abstract_client.ts
> fix: do not shift pings on 'publish' packets

- README.md
fix https://github.com/mqttjs/MQTT.js/issues/1797
> docs: make wechat mini program runnable

- package-lock.json
- package.json
> fix(security): bump ws@8.17.1 and other audit issues

- src/lib/connect/index.ts
> fix(wechat): do not ignore path with `wx` protocol

- src/lib/client.ts
- test/client.ts
> fix: connect after client.end not working

- src/lib/connect/index.ts
see https://github.com/mqttjs/MQTT.js/issues/1824#issuecomment-2145852235
> fix(types): add connectAsync overload signature with allowRetries

- src/lib/BufferedDuplex.ts
- src/lib/connect/ws.ts
> fix(browser): prevent error `stream.push() after EOF`

- src/lib/client.ts
- test/abstract_client.ts
https://github.com/mqttjs/MQTT.js/issues/1510
> feat: add `suback` packet to subscribe callback
